// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzME7pvWLqdlkbGEtgyA2m0eYVlM3noAU',
    appId: '1:261161518519:web:e4d87858a84219d37fd432',
    messagingSenderId: '261161518519',
    projectId: 'project-salad-1cb98',
    authDomain: 'project-salad-1cb98.firebaseapp.com',
    storageBucket: 'project-salad-1cb98.appspot.com',
    measurementId: 'G-724S54XEJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMSW4XTdIk74nfske5joOgwKAfbjqvpB0',
    appId: '1:261161518519:android:b920ec80d59e7d1a7fd432',
    messagingSenderId: '261161518519',
    projectId: 'project-salad-1cb98',
    storageBucket: 'project-salad-1cb98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPwlmN3SUOa5-AEG2_b9gaM49n_dO-hvw',
    appId: '1:261161518519:ios:3cbbd1afd62f75a47fd432',
    messagingSenderId: '261161518519',
    projectId: 'project-salad-1cb98',
    storageBucket: 'project-salad-1cb98.appspot.com',
    iosClientId: '261161518519-3t80fh496s5pe3ovj6kunv7u5tggtncu.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPwlmN3SUOa5-AEG2_b9gaM49n_dO-hvw',
    appId: '1:261161518519:ios:2aa10092139d005c7fd432',
    messagingSenderId: '261161518519',
    projectId: 'project-salad-1cb98',
    storageBucket: 'project-salad-1cb98.appspot.com',
    iosClientId: '261161518519-5i222jj9b24u3vle2c44u59n0vb8t5ro.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
